// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bison.Razor.Migrations
{
    [DbContext(typeof(BisonDbContext))]
    [Migration("20261007120008_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Bison.Razor.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Bison.Razor.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Bison.Razor.Models.Taxon", b =>
                {
                    b.Property<int>("TaxonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DanishVernacularName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DwcTaxonId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaxonId");

                    b.HasIndex("ParentId");

                    b.ToTable("Taxons");
                });

            modelBuilder.Entity("Bison.Razor.Models.Comment", b =>
                {
                    b.HasBaseType("Bison.Razor.Models.Post");

                    b.Property<int>("ObservationId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ObservationId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Bison.Razor.Models.Observation", b =>
                {
                    b.HasBaseType("Bison.Razor.Models.Post");

                    b.Property<int?>("TaxonId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("TaxonId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("Bison.Razor.Models.Proposal", b =>
                {
                    b.HasBaseType("Bison.Razor.Models.Post");

                    b.Property<int>("ObservationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaxonId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ObservationId");

                    b.HasIndex("TaxonId");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("Bison.Razor.Models.Post", b =>
                {
                    b.HasOne("Bison.Razor.Models.Author", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Bison.Razor.Models.Taxon", b =>
                {
                    b.HasOne("Bison.Razor.Models.Taxon", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Bison.Razor.Models.Comment", b =>
                {
                    b.HasOne("Bison.Razor.Models.Observation", "Observation")
                        .WithMany("Comments")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bison.Razor.Models.Post", null)
                        .WithOne()
                        .HasForeignKey("Bison.Razor.Models.Comment", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("Bison.Razor.Models.Observation", b =>
                {
                    b.HasOne("Bison.Razor.Models.Post", null)
                        .WithOne()
                        .HasForeignKey("Bison.Razor.Models.Observation", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bison.Razor.Models.Taxon", "Taxon")
                        .WithMany("Observations")
                        .HasForeignKey("TaxonId");

                    b.Navigation("Taxon");
                });

            modelBuilder.Entity("Bison.Razor.Models.Proposal", b =>
                {
                    b.HasOne("Bison.Razor.Models.Observation", "Observation")
                        .WithMany("Proposals")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bison.Razor.Models.Post", null)
                        .WithOne()
                        .HasForeignKey("Bison.Razor.Models.Proposal", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bison.Razor.Models.Taxon", "Taxon")
                        .WithMany("Proposals")
                        .HasForeignKey("TaxonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");

                    b.Navigation("Taxon");
                });

            modelBuilder.Entity("Bison.Razor.Models.Author", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Bison.Razor.Models.Taxon", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Observations");

                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("Bison.Razor.Models.Observation", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
